version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: monitor_server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw
    ports:
      - "5439:5432"
    restart: unless-stopped

