spring.application.name=monitor

server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5439/monitor_server
spring.r2dbc.username=admin
spring.r2dbc.password=passw

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

#logging.level.org.springframework.r2dbc=DEBUG
#logging.level.io.r2dbc.postgresql.QUERY=DEBUG
#logging.level.io.r2dbc.postgresql.PARAM=DEBUG
#
# monitoring
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# generate in terminal: openssl rand -base64 32
jwt.secret=a+dvLoifq13yAY+URuFcoZfv5PiRwddhLPJ0lbmEq4E=