spring.application.name=monitor

server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/monitor
spring.r2dbc.username=postgres
spring.r2dbc.password=yourpassword

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# monitoring
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always